TonyMultipurpose/TonyMultipurpose/Areas/DoubleBenefit/Controllers/DBMatureEncahmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TonyMultipurpose.Areas.DoubleBenefit.BLL;
using TonyMultipurpose.Areas.DoubleBenefit.Models;
using TonyMultipurpose.Areas.Transaction.BLL;
using TonyMultipurpose.AuthData;

namespace TonyMultipurpose.Areas.DoubleBenefit.Controllers
{
    [AuthenticationFilter]
    public class DBMatureEncahmentController : Controller
    {
        // GET: DoubleBenefit/DBMatureEncahment

        DoubleBenefitBLL objDoubleBenefitBLL = new DoubleBenefitBLL();
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult AutoCompleteAccountNumber(string term)
        {
            var result = objDoubleBenefitBLL.GetDBAccountNumberForAutocomplete(term);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAccountInfoByAccountNo(string AccountNumber)
        {
            var data = objDoubleBenefitBLL.GetDBAccountInfoByAccountNo(AccountNumber);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Save(Doublebenefit objdoubleBenefit)
        {
            bool status = true;

            objDoubleBenefitBLL.SaveDBMatureEncashmentInfo(objdoubleBenefit);

            return new JsonResult { Data = new { status = status } };
        }

        public JsonResult GetUnAppovedDBList(string id)
        {
            bool exsits = objDoubleBenefitBLL.GetUnAppovedDBList(id);
            if (exsits) { return Json(false, JsonRequestBehavior.AllowGet); }
            else { return Json(true, JsonRequestBehavior.AllowGet); }
        }

        public JsonResult GetCloseDBAccount(string id)
        {
            bool exsits = objDoubleBenefitBLL.GetCloseDBAccount(id);
            if (exsits) { return Json(false, JsonRequestBehavior.AllowGet); }
            else { return Json(true, JsonRequestBehavior.AllowGet); }
        }

        public JsonResult GetTransactionalCoaData()
        {
            TransactionBLL objTransactionBll = new TransactionBLL();
            var data = objTransactionBll.GetTransactionalCoaData();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

TonyMultipurpose/TonyMultipurpose/Areas/DoubleBenefit/Views/DBMatureEncahment/Index.cshtml
@model TonyMultipurpose.Areas.DoubleBenefit.Models.Doublebenefit

@{
    ViewBag.Title = "Double Benefit Mature Encashment";
}


@using (Html.BeginForm("Index", "DBMatureEncahment", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    if (Model != null && Model.Id > 0)
    {
        @Html.HiddenFor(d => d.Id)
    }
    <div class="container panel panel-default" style="float: left">
        @*<div class="panel-heading">
            <h3>Double Benefit Mature Encashment</h3>
        </div>*@
        <div class="panel-body">
                <table class="table" style="width: 90%">
                    <tr>
                        <td>
                            <table class="table">
                                <tr>
                                    <td> <label class="control-label">A/C No.</label></td>
                                    <td><input type="text" id="AccountNumber" name="AccountNumber" class="form-control" onkeypress="return IsInteger(event);" placeholder="Type account no" /></td>
                                    <td><span class="error">**</span></td>
                                </tr>
                                <tr>
                                    <td><label class="control-label">Customer Id</label></td>
                                    <td><input type="text" id="CustomerId" name="CustomerId" class="form-control" readonly="readonly" /></td>
                                    <td><span class="error">**</span></td>
                                </tr>

                                <tr>
                                    <td><label class="control-label">Customer Name</label></td>
                                    <td><input type="text" id="CustomerName" class="form-control" readonly="readonly" /></td>
                                    <td><span class="error">**</span></td>
                                </tr>

                                <tr>
                                    <td><label class="control-label">Interest Rate</label></td>
                                    <td><input type="text" id="InterestRate" class="form-control" readonly="readonly" /></td>
                                    <td><span class="error">**</span></td>
                                </tr>

                                <tr>
                                    <td><label class="control-label">Deposit Amount</label></td>
                                    <td><input type="text" id="DepositAmount" name="DepositAmount" class="form-control" readonly="readonly" /></td>
                                    <td><span class="error">**</span></td>
                                </tr>

                                <tr>
                                    <td><label class="control-label">Duration</label></td>
                                    <td><input type="text" id="Duration" name="Duration" class="form-control" readonly="readonly" /></td>
                                    <td><span class="error">**</span></td>
                                </tr>
                                <tr>
                                    <td><label class="control-label">Transaction Date</label></td>
                                    <td>
                                        <input type="text" id="TransactionDate" name="TransactionDate" class="form-control" readonly="readonly" />
                                    </td>
                                    <td><span class="error">**</span></td>
                                </tr>
                                <tr>
                                    <td><label class="control-label">Mature Date</label></td>
                                    <td>
                                        <input type="text" id="MatureDate" name="MatureDate" class="form-control" readonly="readonly" />
                                    </td>
                                    <td><span class="error">**</span></td>
                                </tr>

                                @*<tr>
                                    <td><label class="control-label">Accured Balance</label></td>
                                    <td><input type="text" id="InterestAmount" name="InterestAmount" class="form-control" readonly="readonly" /></td>
                                    <td><span class="error">**</span></td>
                                </tr>*@

                                <tr>
                                    <td><label class="control-label">Mature Amount</label></td>
                                    <td><input type="text" id="MatureAmount" name="MatureAmount" class="form-control" readonly="readonly"/></td>
                                    <td><span class="error">**</span></td>
                                </tr>

                                <tr>
                                    <td><label class="control-label">Paid From</label></td>
                                    <td>
                                        <select name="COAId" id="ChartOfAccount" class="form-control"></select>
                                    </td>
                                    <td><span class="error">**</span></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td>
                                        <label id="message" style="color: red"></label>
                                    </td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td><input id="submit" type="button" value="Withdraw" class="btn btn-success" style="padding: 10px 40px" /></td>

                                </tr>
                            </table>
                        </td>

                        <td>
                            <div class="img-responsive" style="vertical-align: top">
                                <img src="" alt="No Image" width="200px" height="200px" id="CustomerImage" />
                            </div>
                        </td>
                    </tr>
                </table>

        </div>


    </div>
}

@section styles
{
    <style type="text/css">
    .table {
        border-bottom: 0px !important;
    }

        .table th, .table td {
            border: 1px !important;
        }

    .fixed-table-container {
        border: 0px !important;
    }

    .formatedTable td {
        padding-bottom: 6px;
    }

    .formatedTable input {
        padding-right: 210px;
    }

    .container {
        border: none;
    }

    span.error {
        display: block;
        visibility: hidden;
        color: red;
        /*font-weight: bold;*/
        font-size: 100%;
    }
</style>
}

@section scripts
{
    
<script src="~/Scripts/Custom/DoubleBenefit/MatureEncashment.js"></script>
}