TonyMultipurpose/TonyMultipurpose/Areas/DoubleBenefit/Controllers/ApprovalDBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TonyMultipurpose.Areas.DoubleBenefit.BLL;
using TonyMultipurpose.Areas.DoubleBenefit.Models;
using TonyMultipurpose.AuthData;
using TonyMultipurpose.DAL;
using TonyMultipurpose.Models;

namespace TonyMultipurpose.Areas.DoubleBenefit.Controllers
{
    [AuthenticationFilter]
    public class ApprovalDBController : Controller
    {
        private readonly DoubleBenefitBLL _objDoubleBenefitBLL;
        Doublebenefit objDoublebenefit;
        public ApprovalDBController()
        {
            _objDoubleBenefitBLL = new DoubleBenefitBLL();
        }
        // GET: DoubleBenefit/ApprovalDB
        public ActionResult Index()
        {
            objDoublebenefit = new Doublebenefit();
            objDoublebenefit.IsApproved = false;
            //oCSSModel.IsActive = true;
            objDoublebenefit.CompanyId = Convert.ToInt16(SessionUtility.TMSessionContainer.CompanyId);
            List<Doublebenefit> DBTransactions = _objDoubleBenefitBLL.GetDoublebenefitTransactions(objDoublebenefit);
            return View(DBTransactions);
        }
        [HttpPost]
        [MultipleButton(Name = "action", Argument = "Approve")]
        public ActionResult Approve(FormCollection form)
        {
            var ch = form.GetValues("Id");
            if(ch != null)
            {
                _objDoubleBenefitBLL.ApprovedDBTransaction(ch);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "Reject")]
        public ActionResult Reject(FormCollection form)
        {
            List<Doublebenefit> transactions = new List<Doublebenefit>();
            Doublebenefit objDoublebenefit;
            var ids = form.GetValues("Id");
            if (ids != null)
            {
                var totalItem = ids.Length;
                for (int i = 0; i < totalItem; i++)
                {
                    objDoublebenefit = new Doublebenefit();
                    objDoublebenefit.TransactionId = ids[i];
                    objDoublebenefit.RejectReason = form.GetValues(objDoublebenefit.TransactionId)[0];
                    transactions.Add(objDoublebenefit);
                }
                _objDoubleBenefitBLL.RejectDoubleBenefitTransaction(transactions);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Detail(int id)
        {
            if (id == null) return null;
            var doubleBenefitData = _objDoubleBenefitBLL.GetDoublebenefitTransactionsById(id); 
            return View(doubleBenefitData);
        }
       
    }
}

TonyMultipurpose/TonyMultipurpose/Areas/DoubleBenefit/Views/ApprovalDB/Detail.cshtml
@model TonyMultipurpose.Areas.DoubleBenefit.Models.Doublebenefit

@{
    ViewBag.Title = "Double Benefit Transaction Detail";
}

<div class="container panel panel-default" style="float: left">
    <div class="panel-heading"><h2>Double Benefit Info </h2></div>
    <div class="panel-body">
        <table width="100%">

            <tr>
                <td>
                    <table>
                        <tr>
                            <td>
                                <label class="control-label">Transaction Id</label>
                            </td>
                            <td>
                                <input type="text" id="TransactionId" class="form-control" value="@Model.TransactionId" readonly="readonly" />
                                <span class="error">space </span>
                            </td>

                        </tr>

                        <tr>
                            <td>
                                <label class="control-label">Transaction Date</label>
                            </td>
                            <td>
                                <input type="text" id="TransactionDate" class="form-control" value="@Model.TransactionDate.ToString("dd/MMM/yyyy")" readonly="readonly" />
                                <span class="error">space </span>
                            </td>
                        </tr>

                        <tr>
                            <td>
                                <label class="control-label">Customer Id</label>
                            </td>
                            <td>
                                <input type="text" id="CustomerId" class="form-control" value="@Model.CustomerId" readonly="readonly" />
                                <span class="error">space </span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label class="control-label">Name</label>
                            </td>
                            <td>
                                <input type="text" id="CustomerName" class="form-control" value="@Model.CustomerName" readonly="readonly" />
                                <span class="error">space </span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label class="control-label">Father Name</label>
                            </td>
                            <td>
                                <input type="text" id="FatherName" class="form-control" value="@Model.FatherName" readonly="readonly" />
                                <span class="error">space </span>
                            </td>
                        </tr>

                        <tr>
                            <td>
                                <label class="control-label">AccountNumber</label>
                            </td>
                            <td>
                                <input type="text" id="AccountNumber" class="form-control" value="@Model.AccountNumber" readonly="readonly" />
                                <span class="error">space </span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label class="control-label">Center Name</label>
                            </td>
                            <td>
                                <input type="text" id="BranchName" class="form-control" value="@Model.BranchName" readonly="readonly" />
                                <span class="error">space </span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label class="control-label">Transaction Type</label>
                            </td>
                            <td>
                                <input type="text" id="TransactionType" class="form-control" value="@Model.TransactionType" readonly="readonly" />
                                <span class="error">space </span>
                            </td>

                        </tr>
                        <tr>
                            <td>
                                <label class="control-label">Particular</label>
                            </td>
                            <td>
                                <input type="text" id="Particular" class="form-control" value="@Model.Particular" readonly="readonly" />
                                <span class="error">space </span>
                            </td>

                        </tr>

                        <tr>
                            <td>
                                <label class="control-label">InterestRate</label>
                            </td>
                            <td>
                                <input type="text" id="InterestRate" class="form-control" value="@Model.InterestRate" readonly="readonly" />
                                <span class="error">space </span>
                            </td>
                        </tr>

                        <tr>
                            <td>
                                <label class="control-label">Debit</label>
                            </td>
                            <td>
                                <input type="text" id="Debit" class="form-control" value="@Model.Debit" readonly="readonly" />
                                <span class="error">space </span>
                            </td>

                        </tr>

                        <tr>
                            <td>
                                <label class="control-label">Credit</label>
                            </td>
                            <td>
                                <input type="text" id="Credit" class="form-control" value="@Model.Credit" readonly="readonly" />
                                <span class="error">space </span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label class="control-label">Created By</label>
                            </td>
                            <td>
                                <input type="text" id="Username" class="form-control" value="@Model.Username" readonly="readonly" />
                                <span class="error">space </span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                            </td>
                            <td><a class="popup btn btn-primary" href="@Url.Action("Index", "ApprovalDB",new { Area = "DoubleBenefit" })">Back To List</a>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
</div>

@section styles
{
    <style>
    /*Adding some css for looks good*/
        span.error {
            display: block;
            visibility: hidden;
            color: red;
            font-size: 90%;
        }


        /*css for table*/
        .container td {
            vertical-align: top;
        }

        .tablecontainer table {
            width: 100%;
            border-collapse: collapse;
            border-top: 1px solid #BFAEAE;
            border-right: 1px solid #BFAEAE;
        }

        .tablecontainer th {
            border-bottom: 1px solid #BFAEAE !important;
        }

        .tablecontainer th, .tablecontainer td {
            text-align: left;
            border-left: 1px solid #BFAEAE;
            padding: 5px;
            border-bottom: 1px solid #BFAEAE;
        }

        .ui-widget {
            font-size: 12px !important;
        }

        #hideid {
            display: none;
        }
    </style>
}

TonyMultipurpose/TonyMultipurpose/Areas/DoubleBenefit/Views/ApprovalDB/Index.cshtml
@using GridMvc.Html
@model IEnumerable<TonyMultipurpose.Areas.DoubleBenefit.Models.Doublebenefit>
@{
    ViewBag.Title = "Double Benefit Approval";
    var grid = new WebGrid(source: Model, canPage: true,
        canSort: true, rowsPerPage: 1000, ajaxUpdateContainerId: "checkableGrid", ajaxUpdateCallback: "checkBoxHeader();");
    int rowVal = 0;
}

@*<h2>Double Benefit Info </h2>*@
<hr />
<div class="input-group col-md-3">
    <span class="input-group-addon">Search</span>
    <input type="text" id="search" class="form-control" placeholder="search" />
</div>
<hr />
@using (Html.BeginForm("", "ApprovalDB", FormMethod.Post))
{
    <div class="table-responsive">
        @grid.GetHtml(
            tableStyle: "table table-bordered",
            htmlAttributes: new { id = "checkableGrid" },
            columns: grid.Columns
                (
                    //Here I am going to add checkbox column
                    grid.Column("Sr.No.", format: item => rowVal = rowVal + 1),
                    grid.Column(
                        format: @<text> <input type="checkbox" value="@item.TransactionId" name="Id" /> </text>,
                        header: "{checkall}"
                        ),
                    grid.Column("TransactionId", "Transaction Id"),
                    grid.Column("TransactionDate", "Transaction Date", format:
        (item) => string.Format("{0:dd/MMM/yyyy}", item.TransactionDate)),
                    grid.Column("CustomerId", "Customer Id"),
                    grid.Column("CustomerName", "CustomerName"),
                    grid.Column("TransactionType", "Transaction Type"),
                    grid.Column("AccountNumber", "Account Number"),
                    grid.Column("InterestRate", "Interest Rate"),
                    grid.Column("Amount", "Amount"),
                    grid.Column(
                        format: @<text> <input type="text" name="@item.TransactionId" /> </text>,
                        header: "Reject Reason"
                        ),
                     grid.Column("Username", "Created By"),
                    grid.Column(format: @<text>@Html.ActionLink("Detail", "Detail", new { id = @item.Id }, new { target = "_blank" })  </text>,
                        header: "Detail")
                )
            )
    </div>

    <div class="row" style="width:180px;margin-top:10px;">
        <div class="col-md-6">
            <input type="submit" value="Approve" name="action:Approve" onclick="return confirm('Are you Want to Approve?');" class="btn btn-success" />
        </div>
        <div class="col-md-6">
            <input type="submit" value="Reject" name="action:Reject" onclick="return confirm('Are you Want to Reject?');" class="btn btn-google"/>
        </div>
    </div>
}

@section styles
{
   <style type="text/css">
    table.gridtable {
        font-family: verdana,arial,sans-serif;
        font-size: 11px;
        color: #333333;
        border-width: 1px;
        border-color: #666666;
        border-collapse: collapse;
    }

        table.gridtable th {
            border-width: 1px;
            padding: 8px;
            border-style: solid;
            border-color: #666666;
            background-color: #dedede;
        }

        table.gridtable td {
            border-width: 1px;
            padding: 8px;
            border-style: solid;
            border-color: #666666;
            background-color: #ffffff;
        }
</style>
}

@section scripts
{
   
<script src="~/Scripts/Custom/DoubleBenefit/ApprovalIndex.js"></script>
}