TonyMultipurpose/TonyMultipurpose/Models/AssignUserRole.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TonyMultipurpose.Areas.Setup.Models;
using TonyMultipurpose.Models;

namespace TonyMultipurpose.Models
{
    //--ataur
    //==db table name: UserRoleMapping==//
    public class AssignUserRole:CommonModel
    {
        [Key]
        public int UrmId { get; set; }



        [Required(ErrorMessage = "Username Is Required !")]
        [Display(Name = "Username")]
        public short UserDetailId { get; set; }
        public string Username { get; set; }
        public List<UserDetail> userDetail { get; set; }


        [Display(Name = "Role Name")]
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public List<RoleInfo> roleInfo { get; set; }

        [Required(ErrorMessage = "Branch Name Is Required !")]
        [Display(Name = "Branch Name")]
        public short? BranchId { get; set; }
        public string BranchName { get; set; }
        public List<Branch> branchInfo { get; set; }
    }
}

TonyMultipurpose/TonyMultipurpose/Controllers/AssignUserRoleController.cs
using System;
using System.Web.Mvc;
using TonyMultipurpose.Areas.Setup.BLL;
using TonyMultipurpose.AuthData;
using TonyMultipurpose.BLL;
using TonyMultipurpose.Models;

namespace TonyMultipurpose.Controllers
{
    [AuthenticationFilter]
    //--ataur
    public class AssignUserRoleController : Controller
    {
        // GET: Setup/AssignUserRole
        public ActionResult Index(string search = null)
        {
            RoleManagementBLL objRoleManagementBll=new RoleManagementBLL();
            var roleInfo = objRoleManagementBll.GetUserRoleMappingInfo(search);

            return View(roleInfo);
        }


        //Load Username,RoleName,BranchName for save
        [HttpGet]
        public ActionResult GetAllDropdownInfo()
        {
            UserDetailBLL objUserDetailBll = new UserDetailBLL();
            RoleBLL objRoleBll = new RoleBLL();
            BranchBLL objBranchBll = new BranchBLL();
            var model = new AssignUserRole
            {
                userDetail = objUserDetailBll.GetAllUserInfo(),
                roleInfo = objRoleBll.GetAllRoleInfo(),
                branchInfo = objBranchBll.GetAllBranchInfo()
            };
            return View("UserPartial", model);
        }

        [HttpGet]
        public ActionResult Save()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(AssignUserRole objAssignUserRole)
        {
            if (ModelState.IsValid)
            {
                RoleManagementBLL objRoleManagementBll = new RoleManagementBLL();
                objRoleManagementBll.AssignUserRoleInfo(objAssignUserRole);
            }
            return RedirectToAction("Index", "AssignUserRole");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            RoleManagementBLL objRoleManagementBll=new RoleManagementBLL();
            UserDetailBLL objUserDetailBll = new UserDetailBLL();
            RoleBLL objRoleBll = new RoleBLL();
            BranchBLL objBranchBll = new BranchBLL();
            var model = new AssignUserRole
            {
                userDetail = objUserDetailBll.GetAllUserInfo(),
                roleInfo = objRoleBll.GetAllRoleInfo(),
                branchInfo = objBranchBll.GetAllBranchInfo()
            };
            var assignRoleInfo = objRoleManagementBll.GetAssignRoleInfoById(id);
            Session["UrmId"] = assignRoleInfo.UrmId;
            ViewBag.UserDetailId=assignRoleInfo.UserDetailId;
            ViewBag.RoleId = assignRoleInfo.RoleId;
            ViewBag.BranchId = assignRoleInfo.BranchId;
            ViewBag.IsActive = assignRoleInfo.IsActive;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AssignUserRole objAssignUserRole)
        {
            objAssignUserRole.UrmId = Convert.ToInt32(Session["UrmId"]);
            RoleManagementBLL objRoleManagementBll = new RoleManagementBLL();
            if (ModelState.IsValid)
            {
                objRoleManagementBll.UpdateAssignUserRole(objAssignUserRole);
                Session.Remove("UrmId");
            }
            return RedirectToAction("Index", "AssignUserRole");
        }
    }
}

TonyMultipurpose/TonyMultipurpose/Controllers/UserMenuMappingController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TonyMultipurpose.Areas.Setup.BLL;
using TonyMultipurpose.AuthData;
using TonyMultipurpose.BLL;

namespace TonyMultipurpose.Controllers
{
    
    public class UserMenuMappingController : Controller
    {
        [AuthenticationFilter]
        // GET: UserMenuMapping
        [HttpGet]
        public ActionResult Save(int BranchId = 0, int userDetailId = 0, int roleId = 0)
        {           

            BranchBLL objBranchBll = new BranchBLL();
            ViewBag.BranchInfo = objBranchBll.GetAllBranchInfo();

            UserDetailBLL objUserDetailBll = new UserDetailBLL();
            ViewBag.UserInfo = objUserDetailBll.GetAllUserInfo();

            RoleManagementBLL objRoleManagementBll = new RoleManagementBLL();
            ViewBag.RoleInfo = objRoleManagementBll.GetRoleListForDropDownForSave().Where(a => a.RoleId == roleId);


            NavigationBLL objNavigationBll = new NavigationBLL();
            var menu = objNavigationBll.GetAllMenuForUserMenuMapping(userDetailId, roleId);

            return View(menu);
        }


        [HttpPost]
        public JsonResult Save(IEnumerable<int> menuId, int roleId, int userId)
        {
            bool status = false;

            RoleManagementBLL objRoleManagementBll = new RoleManagementBLL();
            if (ModelState.IsValid)
            {
                objRoleManagementBll.ResetUserMenuMapping(roleId, userId);
                if (menuId != null)
                {
                    foreach (int item in menuId)
                    {
                        objRoleManagementBll.CreateUserMenuMapping(item, roleId, userId);
                    }
                }
                status = true;
            }
            return new JsonResult { Data = new { status = status } };
        }

        [AllowAnonymous]
        [HttpPost]
        public JsonResult GetUserByBranchId(int branchId)
        {
            UserDetailBLL _objUserDetailBLL = new UserDetailBLL();
            var u = _objUserDetailBLL.GetAllUserInfo().Where(a => a.BranchId == branchId).ToList();
            return Json(u, JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        [HttpPost]
        public JsonResult GetRoleByUserId(int userDetailId)
        {
            RoleManagementBLL objRoleManagementBll = new RoleManagementBLL();
            var u = objRoleManagementBll.GetRoleByUserId(userDetailId).ToList();
            return Json(u, JsonRequestBehavior.AllowGet);
        }
    }
}

TonyMultipurpose/TonyMultipurpose/Views/AssignUserRole/Edit.cshtml
@model TonyMultipurpose.Models.AssignUserRole
@{
    ViewBag.Title = "Edit Assign User Role";
}


@*<h3>Edit User Role. </h3>
<h4>You can change user role and his/her status.</h4>
<hr />*@

@using (Html.BeginForm("Edit", "AssignUserRole", FormMethod.Post, new { @class = "form-horizontal", @role = "form" }))
{
    @Html.AntiForgeryToken()

    if (Model != null && Model.UrmId > 0)
    {
        @Html.HiddenFor(b => b.UrmId)
    }

    <div class="form-group row">
        @Html.LabelFor(a => a.BranchId, new { @class = "control-label col-sm-2" })
        <div class="col-sm-3">
            @Html.DropDownListFor(
            x => x.BranchId,
            new SelectList(Model.branchInfo, "BranchId", "BranchName"),
            "--Select Branch--", new { @class = "form-control" }
            )
            @Html.ValidationMessageFor(c => c.BranchId, "", new { @class = "text-danger", @style = "color:red" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(a => a.UserDetailId, new { @class = "control-label col-sm-2" })
        <div class="col-sm-3">
            @Html.DropDownListFor(
            x => x.UserDetailId,
            new SelectList(Model.userDetail, "UserDetailId", "UserName"),
            "--Select Username--", new { @class = "form-control" }
            )
            @Html.ValidationMessageFor(c => c.UserDetailId, "", new { @class = "text-danger", @style = "color:red" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(a => a.RoleId, new { @class = "control-label col-sm-2" })
        <div class="col-sm-3">
            @Html.DropDownListFor(
                x => x.RoleId,
                new SelectList(Model.roleInfo, "RoleId", "RoleName"),
                "--Select Role Name--", new { @class = "form-control" }
                )
            @Html.ValidationMessageFor(c => c.RoleId, "", new { @class = "text-danger", @style = "color:red" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(ui => ui.IsActive, new { @class = "control-label col-sm-2" })
        <div class="col-sm-3">
            @Html.DropDownList("IsActive", new List<SelectListItem>()
            {
                new SelectListItem {Text = "Active", Value = "true"},
                new SelectListItem {Text = "Inactive", Value = "false"}
            }, new { @class = "form-control" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
            <button type="submit" class="btn btn-success">Update</button>
        </div>
    </div>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
}

@section scripts
{
    <script>
        $(document).ready(function () {


            $('#BranchId').on('change', function () {

                var branchId = $('#BranchId').val();
                $.ajax({
                    url: '@Url.Action("GetUserByBranchId", "UserMenuMapping")',
                    type: "POST",
                    data: { branchId: branchId },
                    dataType: "json",
                    traditional: true,
                    success: function (d) {
                        $("#UserDetailId").html(""); // clear before appending new list
                        $.each(d, function (i, u) {
                            $("#UserDetailId").append(
                                $('<option></option>').val(u.UserDetailId).html(u.Username));
                        });
                    }
                });
            });
        });
    </script>
}

TonyMultipurpose/TonyMultipurpose/Views/AssignUserRole/Index.cshtml
@using GridMvc.Html
@using TonyMultipurpose.Infrastructure.Common
@using TonyMultipurpose.Infrastructure.Helpers

@model IEnumerable<TonyMultipurpose.Models.AssignUserRole>

@{
    ViewBag.Title = "Assign User Role";
    WebGrid grid = new WebGrid(Model, canPage: true,
       canSort: true, rowsPerPage: 10, ajaxUpdateContainerId: "grdUserRole");
}


@using (Html.BeginForm("Index", "AssignUserRole", FormMethod.Get, new { @class = "form-inline" }))
{

    <div class="form-group">
        <a class="btn btn-primary btn-sm" href="@Url.Action("Save", "AssignUserRole")"> Add New Assign User Role </a>
    </div>
    <div class="form-group">
        <div class="input-group">
            <input type="text" id="search" name="search" class="form-control input-sm search-box" placeholder="Enter Search Keywords" />
            <div class="input-group-btn">
                <button class="btn btn-default btn-sm" type="submit">
                    <i class="glyphicon glyphicon-search"></i>
                </button>
            </div>
        </div>
    </div>
}

<div class="table-responsive">
    @grid.Table(
    tableStyle: "table table-bordered table-striped table-condensed",
        htmlAttributes: new { id = "grdUserRole" },
        columns: grid.Columns
        (
            grid.Column("SL", format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("Username", "User Name"),
            grid.Column("RoleName", "Role"),
            grid.Column("BranchName", "Branch Name"),
            grid.Column("UserStatus", "Status"),           
            grid.Column(style: "grid-action-column", format: @<text>
                <div class="btn-group">
                    <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Select Action <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Edit", "Edit", new { id = item.UrmId }, new { target = "_blank" })</li>
                    </ul>
                </div>
            </text>,
                header: "Action")
        ))


    @grid.PagerList(WebGridPagerModes.All, paginationStyle: "pagination", numericLinksCount: 10)

</div>

@*<div class="code-cut">
    <a class="popup btn btn-primary" href="~/AssignUserRole/Save/0" style="margin-bottom: 20px; margin-top: 20px;">Add New Assign User Role</a>
    @Html.Grid(Model).Columns(columns =>
{
    columns.Add(a => a.Username).Titled("User Name").Sortable(true).Filterable(true);
    columns.Add(a => a.RoleName).Titled("Role").Sortable(true).Filterable(true);
    columns.Add(a => a.BranchName).Titled("Branch Name").Sortable(true).Filterable(true);
    columns.Add(a => a.UserStatus).Titled("Status").Sortable(true).Filterable(true);

    columns.Add()
        .Encoded(false)
        .Sanitized(false)
        .SetWidth(30)
        .RenderValueAs(a => Html.ActionLink("Edit", "Edit", new { id = a.UrmId, @class = "btn btn-primary" })).Titled("<span>Edit</span>");

}).WithPaging(10).Sortable(true)

</div>*@
@section scripts
{
    <script src="@Url.Content("~/Scripts/Custom/Common/AssignUserRoleList.js")"></script>
}
@section styles
{
    <style>
        span.field-validation-error {
            color: red;
        }
    </style>
}

TonyMultipurpose/TonyMultipurpose/Views/AssignUserRole/Save.cshtml
@model TonyMultipurpose.Models.AssignUserRole
@{
    ViewBag.Title = "Add Assign User Role";
}


@*<h3>Assign User Role.</h3>
<h4>Here you can assign a specific role to an user.</h4>
<hr />*@

@using (Html.BeginForm("Save", "AssignUserRole", FormMethod.Post, new { @class = "form-horizontal", @role = "form" }))
{
    @Html.AntiForgeryToken()

    if (Model != null && Model.UrmId > 0)
    {
        @Html.HiddenFor(b => b.UrmId)
    }

    @Html.Action("GetAllDropdownInfo", "AssignUserRole")

    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
            <button type="submit" class="btn btn-success">Save</button>
        </div>
    </div>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
}

TonyMultipurpose/TonyMultipurpose/Views/AssignUserRole/UserPartial.cshtml
@model TonyMultipurpose.Models.AssignUserRole
@{
    Layout = null;
}

<div style="width: 100%">

    <div class="form-group row">
        @Html.LabelFor(a => a.BranchId, new { @class = "control-label col-sm-2" })
        <div class="col-sm-3">
            @Html.DropDownListFor(
            x => x.BranchId,
            new SelectList(Model.branchInfo, "BranchId", "BranchName"),
            "--Select Branch--", new { @class = "form-control" }
            )
            @Html.ValidationMessageFor(c => c.BranchId, "", new { @class = "text-danger", @style = "color:red" })
        </div>
    </div>


    <div class="form-group row">
        @Html.LabelFor(a => a.UserDetailId, new {@class = "control-label col-sm-2"})
        <div class="col-sm-3">
            @Html.DropDownListFor(
                x => x.UserDetailId,
                new SelectList(Model.userDetail, "UserDetailId", "UserName"),
                "--Select Username--", new {@class = "form-control"}
                )
            @Html.ValidationMessageFor(c => c.UserDetailId, "", new {@class = "text-danger", @style = "color:red"})
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(a => a.RoleId, new {@class = "control-label col-sm-2"})
        <div class="col-sm-3">
            @Html.DropDownListFor(
                x => x.RoleId,
                new SelectList(Model.roleInfo, "RoleId", "RoleName"),
                "--Select Role Name--", new {@class = "form-control"}
                )
            @Html.ValidationMessageFor(c => c.RoleId, "", new {@class = "text-danger", @style = "color:red"})
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {


        $('#BranchId').on('change', function () {

            var branchId = $('#BranchId').val();
            $.ajax({
                url: '@Url.Action("GetUserByBranchId", "UserMenuMapping")',
                type: "POST",
                data: { branchId: branchId },
                dataType: "json",
                traditional: true,
                success: function (d) {
                    $("#UserDetailId").html(""); // clear before appending new list
                    $.each(d, function (i, u) {
                        $("#UserDetailId").append(
                            $('<option></option>').val(u.UserDetailId).html(u.Username));
                    });
                }
            });
        });
    });
</script>