TonyMultipurpose/TonyMultipurpose/Areas/FinancialTransactions/Controllers/FTApprovalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TonyMultipurpose.Areas.FinancialTransactions.BLL;
using TonyMultipurpose.Areas.FinancialTransactions.Models;
using TonyMultipurpose.AuthData;
using TonyMultipurpose.DAL;
using TonyMultipurpose.Models;
using TonyMultipurpose.ReportsViewer;

namespace TonyMultipurpose.Areas.FinancialTransactions.Controllers
{
    [AuthenticationFilter]
    public class FTApprovalController : Controller
    {
        FinancialTransactionsModel _objFTModel;
        FinancialTransactionsBLL _objFinancialTransationsBLL;
        // GET: FinancialTransactions/FTApproval
        public ActionResult Index()
        {
            _objFTModel = new FinancialTransactionsModel();
            _objFinancialTransationsBLL = new FinancialTransactionsBLL();
            _objFTModel.IsApproved = false;
            _objFTModel.CompanyId = Convert.ToInt16(SessionUtility.TMSessionContainer.CompanyId);
            List<FinancialTransactionsModel> FinancialTransactionsList = _objFinancialTransationsBLL.GetUnApprovedFinancialTransactionsList(_objFTModel);
            return View(FinancialTransactionsList);
        }
        // GET: FinancialTransactions/ApproveTransaction

        public ActionResult ApproveTransaction()
        {
            return View();
        }

        [HttpGet]
        public ActionResult ApprovedTransactionList()
        {
            _objFTModel = new FinancialTransactionsModel();
            _objFinancialTransationsBLL = new FinancialTransactionsBLL();
            _objFTModel.IsApproved = true;
            var tra =
                _objFinancialTransationsBLL.GetUnApprovedFinancialTransactionsList(_objFTModel).Where(a => a.IsApproved == true);
            return Json(new { data = tra }, JsonRequestBehavior.AllowGet);
        }
        public void PaymentVoucherReport(string VoucherNo, string VoucherType)
        {
            if (VoucherType == "Journal")
            {
                ReportObject.ReportName = "JournalEntryReport";
                ReportObject.VoucherNo = VoucherNo;
                Response.Redirect("~/ReportsViewer/ReportViewer.aspx");
            }
            else if (VoucherType == "Voucher Receipt")
            {
                ReportObject.ReportName = "AccountsRecievableVoucherReport";
                ReportObject.VoucherNo = VoucherNo;
                Response.Redirect("~/ReportsViewer/ReportViewer.aspx");
            }
            else if (VoucherType == "Voucher Payment")
            {
                ReportObject.ReportName = "AccountPaymentVoucherReport";
                ReportObject.LoanId = VoucherNo;
                Response.Redirect("~/ReportsViewer/ReportViewer.aspx");
            }

        }

       

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "Approve")]
        public ActionResult Approve(FormCollection form)
        {
            _objFinancialTransationsBLL = new FinancialTransactionsBLL();
            var ids = form.GetValues("Id");
            if (ids != null)
            {
                _objFinancialTransationsBLL.ApproveFinancialTransactions(ids);
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        [MultipleButton(Name = "action", Argument = "Reject")]
        public ActionResult Reject(FormCollection form)
        {
            List<FinancialTransactionsModel> _objFinancialTransactions = new List<FinancialTransactionsModel>();
            var ids = form.GetValues("Id");
            if (ids != null)
            {
                var totalItem = ids.Length;
                for (int i = 0; i < totalItem; i++)
                {
                    _objFTModel = new FinancialTransactionsModel();
                    _objFTModel.TransactionId = ids[i];
                    _objFTModel.RejectReason = form.GetValues(_objFTModel.TransactionId)[0];
                    _objFinancialTransactions.Add(_objFTModel);
                }
                _objFinancialTransationsBLL = new FinancialTransactionsBLL();
                _objFinancialTransationsBLL.RejectFinancialTransactions(_objFinancialTransactions);
            }
            return RedirectToAction("Index");
        }
    }
}

TonyMultipurpose/TonyMultipurpose/Areas/FinancialTransactions/Views/FTApproval/ApproveTransaction.cshtml
@using GridMvc.Html
@model IEnumerable<TonyMultipurpose.Areas.FinancialTransactions.Models.FinancialTransactionsModel>
@{
    ViewBag.Title = "ApproveTransaction";
}

<h2>Approved Financial Transaction List</h2>
<hr />
@*<div class="tablecontainer table-responsive">*@
<table id="TransactionTable" class="display" cellspacing="0" style="width:100%;">
    <thead>
    <tr>
       
        <th>Transaction Id</th>
        <th>Transaction Date</th>
        <th>Voucher</th>
        <th>Voucher Type</th>
        <th>Particular</th>
        <th>Bank Name</th>
        <th>Client Name</th>
        <th>Supplier Name</th>
        <th>Account Code</th>
        <th>Account Name</th>
        <th>Category Name</th>
        <th>Group Name</th>
        <th>Credit</th>
        <th>Debit</th>
        <th>Voucher Report</th>
    </tr>
    </thead>
</table>
@*</div>*@

@section styles
{
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" />
@*<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css" />*@

<style>
    /*Adding some css for looks good*/
    span.error {
        display: inline-block;
        visibility: hidden;
        color: red;
        font-weight: bold;
        font-size: 130%;
    }

    /*css for table*/
    .container td {
        vertical-align: top;
    }

    .tablecontainer table {
        width: 100%;
        border-collapse: collapse;
        border-top: 1px solid #BFAEAE;
        border-right: 1px solid #BFAEAE;
    }

    .tablecontainer th {
        border-bottom: 1px solid #BFAEAE !important;
    }

    .tablecontainer th, .tablecontainer td {
        text-align: left;
        border-left: 1px solid #BFAEAE;
        padding: 5px;
        border-bottom: 1px solid #BFAEAE;
    }

    .ui-widget {
        font-size: 12px !important;
    }

    #hideid {
        display: none;
    }

    .formatedTable td {
        padding-bottom: 6px;
    }

    .formatedTable input {
        padding-right: 210px;
    }

    .form-group {
        margin-bottom: 7px;
    }
</style>
}

@section scripts
{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    @*<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>*@
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>

    <script src="~/Scripts/Custom/FinancialTransactions/FTApproval/ApproveTransaction.js"></script>
}

TonyMultipurpose/TonyMultipurpose/Areas/FinancialTransactions/Views/FTApproval/Index.cshtml
@using GridMvc.Html
@model IEnumerable<TonyMultipurpose.Areas.FinancialTransactions.Models.FinancialTransactionsModel>
@{
    ViewBag.Title = "Financial Transactions Approval";
    var grid = new WebGrid(source: Model, canPage: true,
        canSort: true, rowsPerPage: 1000, ajaxUpdateContainerId: "checkableGrid", ajaxUpdateCallback: "checkBoxHeader();");
    int rowVal = 0;
}


@* Here  I am going to add some css for better looks *@



@*<h2>Financial Transaction Approval</h2>*@
<hr />
<div class="input-group col-md-3">
    <span class="input-group-addon">Search</span>
    <input type="text" id="search" class="form-control" placeholder="search" />
</div>
<hr />
@using (Html.BeginForm("", "FTApproval", FormMethod.Post))
{
    <div class="table-responsive">
        @grid.GetHtml(
            tableStyle: "table table-bordered table-condensed",
            htmlAttributes: new { id = "checkableGrid" },
            columns: grid.Columns
                (
                    //Here I am going to add checkbox column
                    grid.Column("Sr.No.", format: item => rowVal = rowVal + 1),
                    grid.Column(
                        format: @<text> <input type="checkbox" value="@item.TransactionId" name="Id" /> </text>,
                        header: "{checkall}"
                        ),
                    grid.Column("TransactionId", "Transaction Id"),
                    grid.Column("TransactionDate", "Transaction Date", format:
        (item) => string.Format("{0:dd/MMM/yyyy}", item.TransactionDate)),
                    grid.Column("VoucherNo", "Voucher"),
                    grid.Column("VoucherType", "Voucher Type"),
                    grid.Column("Particular", "Particular"),
                    grid.Column("BankName", "Bank Name"),
                    grid.Column("ClientName", "Client Name"),
                    grid.Column("SupplierName", "Supplier Name"),
                    grid.Column("AccountCode", "AccountCode"),
                    grid.Column("AccountName", "Account Name"),
                    grid.Column("CategoryName", "Category Name"),
                    grid.Column("GroupName", "Group Name"),
                    grid.Column("Credit", "Credit"),
                    grid.Column("Debit", "Debit"),
                    grid.Column(
                        format: @<text> <input type="text" name="@item.TransactionId" /> </text>,
                        header: "Reject Reason"
                        ),
                     grid.Column("CreatedName", "Created Name"),
                    grid.Column(format: @<text>@Html.ActionLink("Detail", "Details", "FinancialTransaction", new { VoucherNo = @item.VoucherNo }, new { target = "_blank" })  </text>,
                        header: "Detail")
                )
            )
    </div>

    <div class="row" style="width:180px;margin-top:10px;">
        <div class="col-md-6">
            <input type="submit" value="Approve" name="action:Approve" class="btn btn-success" />
        </div>
        <div class="col-md-6">
            <input type="submit" value="Reject" name="action:Reject" class="btn btn-success" />
        </div>
    </div>
}

@section styles
{
    <style type="text/css">
        
         table.gridtable {
             font-family: verdana,arial,sans-serif;
             font-size: 11px;
             color: #333333;
             border-width: 1px;
             border-color: #666666;
             border-collapse: collapse;
         }

        table.gridtable th {
            border-width: 1px;
            padding: 8px;
            border-style: solid;
            border-color: #666666;
            background-color: #dedede;
        }

        table.gridtable td {
            border-width: 1px;
            padding: 8px;
            border-style: solid;
            border-color: #666666;
            background-color: #ffffff;
        }
    </style>
}

@* Here I am going to add some Jquery Code *@

@section scripts
{

    <script src="~/Scripts/Custom/FinancialTransactions/FTApproval/Index.js"></script>

}